name: GCS Deployment
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    name: Deploy Cloud Workflow
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
    - name: Auth
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Using setup-gcloud
      uses: 'google-github-actions/setup-gcloud@v2'
    - name: Overwrite code files in GCS
      run: |
        gsutil -m rm -rf gs://github_code_deployment/code/ || true
        gsutil  -m cp -r code gs://github_code_deployment/